# Generated by Django 5.1.4 on 2024-12-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_level', models.IntegerField()),
                ('teaching_style', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('engagement_score', models.FloatField()),
                ('availability_start', models.TimeField()),
                ('availability_end', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_name', models.CharField(max_length=100)),
                ('mentee_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.mentor')),
            ],
        ),
    ]
