# Generated by Django 5.1.4 on 2024-12-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='strength',
            new_name='skill_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='time_available',
            new_name='time_availability',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='professionalism_level',
            field=models.CharField(choices=[('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Intermediate', max_length=20),
            preserve_default=False,
        ),
    ]
