# Generated by Django 5.1.4 on 2024-12-21 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='professionalism_level_needed',
            field=models.CharField(choices=[('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
