# Generated by Django 5.1.4 on 2024-12-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_collaborationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='time_availability',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
    ]
