# Generated by Django 5.1.4 on 2024-12-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_message_delete_collaborationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
